### ISSUE TITLE
اولین ایشو

### ISSUE THREAD

**Issue by Aryandecoder** [mahdi-tavakoli-anodyneGROUP/Collage-AI-3#1]
سلام مهندس
پروژه رو کم کم باید شیفت بدیم اینجا...
اسمو درست انتخاب کردم؟😁

**Comment by mahdi-tavakoli-anodyneGROUP** [comment]
سلام بله فقط اگه ایشو ها فارسی باشه خیلی عالی تر هم میشه

**Comment by Aryandecoder** [comment]
سلام آقای مهندس.
چشم😅

**Comment by Aryandecoder** [comment]
نام ایشو به فارسی تغییر یافت.
